//
//=======================================================
// Now include files for individual types of initial data
//=======================================================
//
#include "InData.h"
#include "INDATA/LinWave.h"
#include "INDATA/Schwarzschild.h"
#include "INDATA/Flat.h"
#include "INDATA/TOV.h"
#include "INDATA/Trumpet.h"
#include "INDATA/RNS.h"
#include "INDATA/Brill.h"
#include "INDATA/Kerr.h"
#include "INDATA/BowenYork.h"
#include "INDATA/KerrSchild.h"
#include "INDATA/KenTrumpet.h"
#include "INDATA/BrillLindquist.h"
#include "INDATA/Shock.h"
#include "INDATA/EvansColeman.h"
#include "INDATA/Rad_TOV.h"
#include "INDATA/OS.h"
#include "INDATA/RotPerfectFluid.h"
#include "INDATA/Choptuik.h"
#include "INDATA/EMWave.h"
#include "INDATA/RadHydroShockTest.h"
#include "INDATA/Bondi.h"
#include "INDATA/TOV_BH.h"
#include "INDATA/SMS_TOV.h"
#include "INDATA/GaugeWave.h"
#include "INDATA/WindTunnel.h"
#include "INDATA/ReadFromCheckPoint.h"
#include "INDATA/ShibataWave.h"
#include "INDATA/Disk.h"
#include "INDATA/DualEMWave.h"